apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  type: NodePort  # Use NodePort since LoadBalancer isn't available in KinD
  selector:
    app: jupyterhub
  ports:
    - protocol: TCP
      port: 8000        # Internal container port
      targetPort: 8000  # Maps to JupyterHub's container port
      nodePort: 30080   # Exposes JupyterHub on host's port 8080
